---
title: "HW1"
author: "Amosov Artem"
date: "04 04 2022"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(sp)
```

**Task**: find the area of a figure bounded by curves given by the equation:

$$
 y = 2|x| - \pi, x \in [-{pi\over2},{pi\over2}]
$$
$$
 y = |sin(2x)|, x \in [-{pi\over 2},{pi\over 2}]
$$

```{r fig.align="center", echo = FALSE,fig.width = 14,fig.height=10}
X <- seq(from=-pi/2, to=pi/2, by = 0.01)
Y1 <- 2*abs(X) - pi
Y2 <- abs(sin(2*X))
df <- data.frame(X, Y1, Y2)

ggplot(df, aes(X))+
  geom_line(aes(X,Y1), color = 'red')+
  geom_line(aes(X,Y2), color = 'red')
```



### Generation of random points
```{r}
coords <- function(){
  x <- runif(10000, min = -pi/2, max = pi/2)
  y <- runif(10000, min = -pi, max = 1)
  Y1 <- abs(sin(2*x))
  Y2 <- 2*abs(x) - pi
  inside <- (y<Y1)&(y>Y2)
  df2 <- data.frame(x, y,inside, Y1, Y2)
  df2
}
points <- coords()
ggplot(points, aes(x))+
  geom_point(aes(x,y, col = inside))+
  geom_line(aes(x,Y1), color = 'black')+
  geom_line(aes(x,Y2), color = 'black')
```

### Counting area
```{r}
inside <- nrow(points[points$inside == T,])
area <- pi*(pi+1)*(inside/10000)
area
```

